"""DO NOT MODIFY. Auto-generated by script/fingerprint_frontend."""

FINGERPRINTS = {
    "compatibility.js": "8e4c44b5f4288cc48ec1ba94a9bec812",
    "core.js": "d4a7cb8c80c62b536764e0e81385f6aa",
    "frontend.html": "24b75edc7053d66b15943045c2c4eab9",
    "mdi.html": "e91f61a039ed0a9936e7ee5360da3870",
    "micromarkdown-js.html": "93b5ec4016f0bba585521cf4d18dec1a",
    "panels/ha-panel-automation.html": "67d03875f7013c1bdb0f47f24eb218e6",
    "panels/ha-panel-config.html": "d951a87490ecd20d3aa98d537e54c0b1",
    "panels/ha-panel-dev-event.html": "b5ab9a53121d6b535682e8c041879ef3",
    "panels/ha-panel-dev-info.html": "e2781f2e885410cbf59fd0005269ce3d",
    "panels/ha-panel-dev-service.html": "1da99110e7af2bc2bb3a2c869a67cec5",
    "panels/ha-panel-dev-state.html": "dbc26402cf36610202bb3131bf594da8",
    "panels/ha-panel-dev-template.html": "109f43c58cb1c3e7d9926be2e6bd260c",
    "panels/ha-panel-hassio.html": "262d31efd9add719e0325da5cf79a096",
    "panels/ha-panel-history.html": "6506895f8ce465bf71db578fa95e222a",
    "panels/ha-panel-iframe.html": "d920f0aa3c903680f2f8795e2255daab",
    "panels/ha-panel-kiosk.html": "2ac2df41bd447600692a0054892fc094",
    "panels/ha-panel-logbook.html": "a180c2b737d3a2a7074d0531f49ec277",
    "panels/ha-panel-map.html": "83c16e9e441e6d17c35e82b6a861119e",
    "panels/ha-panel-zwave.html": "3710c2be1e69d93518b701d4a4446dca"
}
